version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb-bms
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bms
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    ports:
      - "33306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=0

  redis:
    image: redis:7-alpine
    container_name: redis-bms
    ports:
      - "36379:6379"
    volumes:
      - redis_bms_data:/data
    restart: always


volumes:
  mariadb_data:
  redis_bms_data:
