spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    initialization-mode: always
    defer-datasource-initialization: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:23306/bms
    username: root
    password: sangs#1234

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE